Give all old forms a created and updated date
alphagov/forms-api pull request #57
Opened 2022-08-17 17:04 UTC by 0atman

Thanks to @thomasiles for suggesting this in #43

2022-08-18 08:07 UTC, DavidBiddle approved these changes
Looks good to me 🎉

2022-08-18 08:12 UTC, 0atman commented
Do merge this before Monday if you would like the migration to happen. Otherwise I'll do so then!

2022-08-18 08:14 UTC, 0atman commented on spec/db/migration_7_spec.rb
> +    @database[:forms].where(created_at: nil).update(
Wait don't merge, I just noticed I don't explicityly create any test cases. Though there SHOULD be stuff in the db to test, I'd want to add some.

2022-08-18 08:14 UTC, 0atman commented
oh good my change failed rubocop, please don't fix!

2022-08-18 08:14 UTC, aliuk2012 requested changes
Am I missing something, where is the migration 7 file?

2022-08-18 09:53 UTC, 0atman commented
It's dB test 7, not migration test 7. Maybe that naming is confusing...

On August 18, 2022, GitHub ***@***.***> wrote:
> @aliuk2012 requested changes on this pull request.
>
> Am I missing something, where is the migration 7 file?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/alphagov/forms-api/pull/57#pullrequestreview-
1076887891>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAA33MNMOBGIFAR6YLATLFTVZXWI7ANCNFSM562I46JA>.
You are receiving this because you were assigned.Message ID:
***@***.***>

2022-08-22 13:28 UTC, aliuk2012 commented on Dockerfile
> +CMD bundle exec rackup
I dont think this should of been part of your changes

2022-08-22 13:28 UTC, aliuk2012 commented on Gemfile
> +gem "sentry-ruby", "~> 5.4.0"
I dont think this should of been part of your changes

2022-08-22 13:28 UTC, aliuk2012 commented on manifest.yml
> +      PAAS_ENVIRONMENT: ((PAAS_ENVIRONMENT))
I dont think this should of been part of your changes

2022-08-22 13:40 UTC, closed without merging

2022-08-22 13:41 UTC, 0atman commented
sorry folks I'm not used to the new merge strategy on git yet, I pulled in some commits from main that I'm to lazy to remove. New PR incoming

2022-08-22 13:42 UTC, 0atman commented
https://github.com/alphagov/forms-api/pull/60